name: GitHub CI

on:
  schedule:
    - cron:  "0 0 * * 0"
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build live iso
        run: sudo /bin/bash build.sh

      - name: Push to Firefox Send
        run: /bin/bash ffsend.sh
        env:
          WXPUSHER_APPTOKEN: ${{ secrets.WXPUSHER_APPTOKEN }}
          WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}
